Repository inf112-v21/BalmersPeak, pull requests merged in 2021-02, with the labels that each got.

#8 Config/travis ci
  .travis.yml
  README.md
Labels: enhancement

#9 Fix/pomfix
  pom.xml
  src/main/java/inf112/BalmersPeak/app/HelloWorld.java
  src/main/java/inf112/BalmersPeak/app/Main.java
  src/test/java/inf112/BalmersPeak/app/AppTest.java
Labels: enhancement

#11 Fix/improve readme
  README.md
  assets/logo.jpg
  assets/roborally.png
Labels: documentation

#15 laste opp oblig1
  Deliverables/ObligatoriskOppgave1.md
  src/main/java/inf112/BalmersPeak/app/MapHandler.java
Labels: documentation

#17 fix bug where player was stuck when died or won
  src/main/java/inf112/BalmersPeak/app/GUI.java
  src/main/java/inf112/BalmersPeak/app/InputHandler.java
  src/main/java/inf112/BalmersPeak/app/MapHandler.java
Labels: bug

#32 Bug/boundsandtexture
  src/main/java/inf112/BalmersPeak/app/Menu/GameScreen.java
Labels: bug

#33 Robot/functionality
  src/main/java/inf112/BalmersPeak/app/Board/Board.java
  src/main/java/inf112/BalmersPeak/app/Flag/Flag.java
  src/main/java/inf112/BalmersPeak/app/GUI.java
  src/main/java/inf112/BalmersPeak/app/MapHandler.java
  src/main/java/inf112/BalmersPeak/app/Robot/Direction.java
  src/main/java/inf112/BalmersPeak/app/Robot/IRobot.java
  src/main/java/inf112/BalmersPeak/app/Robot/Robot.java
Labels: enhancement

#35 Cardimplementation
  Deliverables/ObligatoriskOppgave1.md
  src/main/java/inf112/balmerspeak/app/GUI.java
  src/main/java/inf112/balmerspeak/app/InputHandler.java
  src/main/java/inf112/balmerspeak/app/Main.java
  src/main/java/inf112/balmerspeak/app/MapHandler.java
  src/main/java/inf112/balmerspeak/app/Volume.java
  src/main/java/inf112/balmerspeak/app/board/Board.java
  src/main/java/inf112/balmerspeak/app/cards/CardSelector.java
  src/main/java/inf112/balmerspeak/app/cards/CardTypes.java
  src/main/java/inf112/balmerspeak/app/cards/Deck.java
  src/main/java/inf112/balmerspeak/app/cards/GeneralCard.java
  src/main/java/inf112/balmerspeak/app/cards/ICards.java
  src/main/java/inf112/balmerspeak/app/cards/MovementCard.java
  src/main/java/inf112/balmerspeak/app/cards/MovementType.java
  src/main/java/inf112/balmerspeak/app/cards/ProgramCard.java
  src/main/java/inf112/balmerspeak/app/cards/Rotation.java
  src/main/java/inf112/balmerspeak/app/cards/RotationCard.java
  src/main/java/inf112/balmerspeak/app/cards/Turning.java
  src/main/java/inf112/balmerspeak/app/flag/Flag.java
  src/main/java/inf112/balmerspeak/app/menu/GameScreen.java
  src/main/java/inf112/balmerspeak/app/menu/MainScreen.java
  src/main/java/inf112/balmerspeak/app/menu/MenuScreen.java
  src/main/java/inf112/balmerspeak/app/menu/OptionsScreen.java
  src/main/java/inf112/balmerspeak/app/menu/RulesScreen.java
  src/main/java/inf112/balmerspeak/app/menu/Screens.java
  src/main/java/inf112/balmerspeak/app/robot/Direction.java
  src/main/java/inf112/balmerspeak/app/robot/IRobot.java
  src/main/java/inf112/balmerspeak/app/robot/Robot.java
  src/test/java/inf112/balmerspeak/app/AppTest.java
Labels: enhancement
