Repository inf112-v21/BalmersPeak, pull requests merged in 2021-03, with the labels that each got.

#43 Cards/g UI
  assets/default/README.md
  assets/default/preview-large.png
  assets/default/preview.png
  assets/default/raw/check-off.png
  assets/default/raw/check-on.png
  assets/default/raw/cursor.9.png
  assets/default/raw/default-pane-noborder.9.png
  assets/default/raw/default-pane.9.png
  assets/default/raw/default-rect-down.9.png
  assets/default/raw/default-rect-pad.9.png
  assets/default/raw/default-rect.9.png
  assets/default/raw/default-round-down.9.png
  assets/default/raw/default-round-large.9.png
  assets/default/raw/default-round.9.png
  assets/default/raw/default-scroll.9.png
  assets/default/raw/default-select-selection.9.png
  assets/default/raw/default-select.9.png
  assets/default/raw/default-slider-knob.png
  assets/default/raw/default-slider.9.png
  assets/default/raw/default-splitpane-vertical.9.png
  assets/default/raw/default-splitpane.9.png
  assets/default/raw/default-window.9.png
  assets/default/raw/default.png
  assets/default/raw/pack.json
  assets/default/raw/selection.png
  assets/default/raw/textfield.9.png
  assets/default/raw/tree-minus.png
  assets/default/raw/tree-plus.png
  assets/default/raw/white.png
  assets/default/skin/default.fnt
  assets/default/skin/uiskin.atlas
  assets/default/skin/uiskin.json
  assets/default/skin/uiskin.png
  pom.xml
  src/main/java/inf112/balmerspeak/app/Main.java
  src/main/java/inf112/balmerspeak/app/MapHandler.java
  src/main/java/inf112/balmerspeak/app/cards/CardSelector.java
  src/main/java/inf112/balmerspeak/app/cards/CardTypes.java
  src/main/java/inf112/balmerspeak/app/cards/Deck.java
  src/main/java/inf112/balmerspeak/app/cards/GeneralCard.java
  src/main/java/inf112/balmerspeak/app/cards/ICards.java
  src/main/java/inf112/balmerspeak/app/cards/MovementCard.java
  src/main/java/inf112/balmerspeak/app/cards/RotationCard.java
  src/main/java/inf112/balmerspeak/app/cards/Turning.java
  src/main/java/inf112/balmerspeak/app/menu/CardImage.java
  src/main/java/inf112/balmerspeak/app/menu/GameScreen.java
  src/main/java/inf112/balmerspeak/app/robot/IRobot.java
  src/main/java/inf112/balmerspeak/app/robot/Robot.java
Labels: enhancement

#47 Tests/decktests
  src/main/java/inf112/balmerspeak/app/cards/CardSelector.java
  src/main/java/inf112/balmerspeak/app/cards/Deck.java
  src/main/java/inf112/balmerspeak/app/menu/GameScreen.java
  src/test/java/inf112/balmerspeak/app/DeckTest.java
Labels: enhancement

#46 Feature/multiplayer
  assets/images/cards/left.jpg
  assets/images/cards/move1.png
  assets/images/cards/move2.png
  assets/images/cards/move3.png
  assets/images/cards/right.jpg
  assets/images/cards/uturn.jpg
  assets/skins/quantum/skin/quantum-horizon-ui.json
  pom.xml
  src/main/java/inf112/balmerspeak/app/GUI.java
  src/main/java/inf112/balmerspeak/app/menu/GameScreen.java
  src/main/java/inf112/balmerspeak/app/menu/LobbyScreen.java
  src/main/java/inf112/balmerspeak/app/menu/MainScreen.java
  src/main/java/inf112/balmerspeak/app/menu/MenuScreen.java
  src/main/java/inf112/balmerspeak/app/menu/Screens.java
  src/main/java/inf112/balmerspeak/app/menu/StartScreen.java
  src/main/java/inf112/balmerspeak/app/network/GameClient.java
  src/main/java/inf112/balmerspeak/app/network/GameServer.java
  src/main/java/inf112/balmerspeak/app/network/IPFinder.java
Labels: enhancement

#48 Fix/unused
  src/main/java/inf112/balmerspeak/app/menu/GameScreen.java
Labels: enhancement

#62 Pushers/functionality
  src/main/java/inf112/balmerspeak/app/board/Pusher.java
  src/main/java/inf112/balmerspeak/app/board/Wrench.java
  src/main/java/inf112/balmerspeak/app/robot/Robot.java
  src/test/java/inf112/balmerspeak/app/PusherTest.java
  src/test/java/inf112/balmerspeak/app/WrenchTest.java
Labels: enhancement

#63 Feature/gu iupgrade
  assets/images/background.png
  assets/images/card.png
  assets/images/cards/left.jpg
  assets/images/cards/left.png
  assets/images/cards/move-1.png
  assets/images/cards/right.jpg
  assets/images/cards/right.png
  assets/images/cards/uturn.jpg
  assets/images/cards/uturn.png
  assets/images/health_token.png
  assets/images/lifetoken.jpg
  assets/images/lifetoken.png
  assets/images/root.png
  src/main/java/inf112/balmerspeak/app/cards/MovementCard.java
  src/main/java/inf112/balmerspeak/app/cards/RotationCard.java
  src/main/java/inf112/balmerspeak/app/menu/GameScreen.java
  src/main/java/inf112/balmerspeak/app/robot/Robot.java
Labels: enhancement

#65 Belt/functionality
  src/main/java/inf112/balmerspeak/app/MapHandler.java
  src/main/java/inf112/balmerspeak/app/board/ConveyorBelt.java
  src/main/java/inf112/balmerspeak/app/board/ExpressConveyorBelt.java
  src/main/java/inf112/balmerspeak/app/board/Pusher.java
  src/main/java/inf112/balmerspeak/app/board/RoundType.java
  src/main/java/inf112/balmerspeak/app/board/Wrench.java
  src/test/java/inf112/balmerspeak/app/ConveyorBeltTest.java
  src/test/java/inf112/balmerspeak/app/PusherTest.java
  src/test/java/inf112/balmerspeak/app/WrenchTest.java
Labels: enhancement

#67 fikset outofbounds bug
  src/main/java/inf112/balmerspeak/app/board/Board.java
  src/main/java/inf112/balmerspeak/app/board/Gear.java
  src/main/java/inf112/balmerspeak/app/board/Hole.java
  src/main/java/inf112/balmerspeak/app/board/Laser.java
  src/main/java/inf112/balmerspeak/app/menu/GameScreen.java
  src/main/java/inf112/balmerspeak/app/robot/FlagComparator.java
  src/main/java/inf112/balmerspeak/app/robot/Robot.java
Labels: bug

#69 Feature/walls
  src/main/java/inf112/balmerspeak/app/MapHandler.java
  src/main/java/inf112/balmerspeak/app/board/Board.java
  src/main/java/inf112/balmerspeak/app/board/IObjects.java
  src/main/java/inf112/balmerspeak/app/board/Map.java
  src/main/java/inf112/balmerspeak/app/board/Walls.java
  src/main/java/inf112/balmerspeak/app/flag/Flag.java
  src/main/java/inf112/balmerspeak/app/menu/GameScreen.java
  src/main/java/inf112/balmerspeak/app/robot/Robot.java
Labels: enhancement

#71 Added direction tests for walls
  src/test/java/inf112/balmerspeak/app/WallsTest.java
Labels: enhancement

#72 Conveyor/functionality
  src/main/java/inf112/balmerspeak/app/board/Board.java
  src/main/java/inf112/balmerspeak/app/board/ConveyorBelt.java
  src/main/java/inf112/balmerspeak/app/board/ConveyorMovementTypes.java
  src/main/java/inf112/balmerspeak/app/board/ExpressConveyorBelt.java
  src/main/java/inf112/balmerspeak/app/board/Wrench.java
  src/main/java/inf112/balmerspeak/app/menu/GameScreen.java
  src/test/java/inf112/balmerspeak/app/WrenchTest.java
Labels: enhancement

#73 Feature/networking
  assets/images/robots/robot0.png
  assets/images/robots/robot1.png
  assets/images/robots/robot2.png
  assets/images/robots/robot3.png
  assets/images/robots/robot4.png
  assets/map/map.tmx
  in-project-repo/com/dosse/WaifUPnP/1.0/WaifUPnP-1.0.jar
  in-project-repo/com/dosse/WaifUPnP/1.0/WaifUPnP-1.0.jar.md5
  in-project-repo/com/dosse/WaifUPnP/1.0/WaifUPnP-1.0.jar.sha1
  in-project-repo/com/dosse/WaifUPnP/1.0/WaifUPnP-1.0.pom
  in-project-repo/com/dosse/WaifUPnP/1.0/WaifUPnP-1.0.pom.md5
  in-project-repo/com/dosse/WaifUPnP/1.0/WaifUPnP-1.0.pom.sha1
  in-project-repo/com/dosse/WaifUPnP/maven-metadata.xml
  in-project-repo/com/dosse/WaifUPnP/maven-metadata.xml.md5
  in-project-repo/com/dosse/WaifUPnP/maven-metadata.xml.sha1
  pom.xml
  src/main/java/inf112/balmerspeak/app/GUI.java
  src/main/java/inf112/balmerspeak/app/Game.java
  src/main/java/inf112/balmerspeak/app/MapHandler.java
  src/main/java/inf112/balmerspeak/app/Player.java
  src/main/java/inf112/balmerspeak/app/board/Board.java
  src/main/java/inf112/balmerspeak/app/board/ConveyorBelt.java
  src/main/java/inf112/balmerspeak/app/board/Map.java
  src/main/java/inf112/balmerspeak/app/cards/CardSelector.java
  src/main/java/inf112/balmerspeak/app/cards/CardTypes.java
  src/main/java/inf112/balmerspeak/app/cards/Deck.java
  src/main/java/inf112/balmerspeak/app/cards/GeneralCard.java
  src/main/java/inf112/balmerspeak/app/cards/ProgramCard.java
  src/main/java/inf112/balmerspeak/app/cards/Turning.java
  src/main/java/inf112/balmerspeak/app/menu/GameScreen.java
  src/main/java/inf112/balmerspeak/app/menu/LobbyScreen.java
  src/main/java/inf112/balmerspeak/app/menu/MainScreen.java
  src/main/java/inf112/balmerspeak/app/menu/StartScreen.java
  src/main/java/inf112/balmerspeak/app/network/GameClient.java
  src/main/java/inf112/balmerspeak/app/network/GameServer.java
  src/main/java/inf112/balmerspeak/app/network/messages/CardExecutedMsg.java
  src/main/java/inf112/balmerspeak/app/network/messages/HandMsg.java
  src/main/java/inf112/balmerspeak/app/network/messages/InitMsg.java
  src/main/java/inf112/balmerspeak/app/network/messages/NumPlayers.java
  src/main/java/inf112/balmerspeak/app/network/tools/CoordsResolver.java
  src/main/java/inf112/balmerspeak/app/network/tools/IPFinder.java
  src/main/java/inf112/balmerspeak/app/robot/FlagComparator.java
  src/main/java/inf112/balmerspeak/app/robot/Robot.java
  src/test/java/inf112/balmerspeak/app/menu/GameScreenTest.java
Labels: enhancement

#74 Fikset testene til Conveyorbelt og wrench
  src/test/java/inf112/balmerspeak/app/ConveyorBeltTest.java
  src/test/java/inf112/balmerspeak/app/WrenchTest.java
Labels: enhancement

#75 fjernet litt ubrukt kode, og addet uml diagram og md fil for oblig3
  Deliverables/ObligatoriskOppgave3.md
  Deliverables/Robo Rally UML.png
  src/main/java/inf112/balmerspeak/app/menu/CardImage.java
Labels: documentation
